modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "backported"
version = "${version}"
displayName = "Backported"
authors = "Dandi2k8"
description = '''
A mod that backports everything from other versions to the most popular modding versions.
'''
logoFile = "icon.png"
mixinConfigs = [
    "backported.mixins.json"
]

[[dependencies.backported]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backported]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backported]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backported]]
modId = "trimmed"
mandatory = true
versionRange = "[2.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backported]]
modId = "sherdsapi"
mandatory = true
versionRange = "[4.0.4,)"
ordering = "AFTER"
side = "BOTH"
